<?php

namespace CMS\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;

/**
 * MediaCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaCategoryRepository extends EntityRepository
{

    /**
     * @param type $limit    limit
     * @param type $offset   offset
     * @param type $criteria criteria
     * @param type $orderBy  orderBy
     *
     * @return type
     */
    public function getList($limit = null, $offset = null, $criteria = array(), $orderBy = array())
    {
        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * get total
     *
     * @return type
     */
    public function getTotal()
    {
        $rst = $this->findAll();
        
        return count($rst);
    }

    /**
     * Adding new language from entity
     *
     * @param \CMS\Bundle\AdminBundle\Entity\MediaCategory $entity
     *
     * @return int $id
     */
    public function addByEntity(\CMS\Bundle\AdminBundle\Entity\MediaCategory $entity)
    {
        $em = $this->getEntityManager();
        $id = 0;
        if (is_object($entity)) {
            $em->persist($entity);
            $em->flush();
            $id = $entity->getId();
        }

        return $id;
    }

    /**
     * Delete item by array id
     *
     * @param array $ids
     *
     * @return array
     */
    public function deleteByIds($ids = array())
    {
        $em = $this->getEntityManager();
        $rst = array();
        if (is_array($ids) && count($ids)) {
            foreach ($ids as $id) {
                $entity = $this->find($id);
                $em->remove($entity);
                if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                    $rst[] = $id;
                }
            }
            $em->flush();
        }

        return $rst;
    }
}
