parameters:
#    cms_web.example.class: CMS\Bundle\WebBundle\Example

services:
#    cms_web.example:
#        class: %cms_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
